# Generated by Django 4.0.3 on 2022-04-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=106)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='anime_images')),
                ('date', models.CharField(max_length=50)),
                ('chapters', models.IntegerField()),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
